/**
 * `vram-toggle` — prove the `vram_toggle` OS service routine (generated by
 * `vramGlue` when a SECOND tilemap is supplied) actually flips the display to
 * the alt map on the REAL snes9x core.
 *
 * The differential: build ONE VRAM blob holding two distinct screens —
 *   * primary tilemap: every cell → tile 0 (white),
 *   * alt tilemap:     every cell → tile 1 (red),
 * both with the SAME two char tiles + palette. The generated glue therefore
 * has BOTH maps in VRAM (at two SCBase windows) and a `vram_toggle` routine
 * that EORs BG0SC's SCBase window to move between them.
 *
 *   ROM A:  `jsr vram_load` then idle  → screen = primary (WHITE).
 *   ROM B:  `jsr vram_load` / `jsr vram_toggle` then idle → screen = alt (RED).
 *
 * Same blob, same glue, only difference is the single `vram_toggle` call. If
 * the routine works, A renders white and B renders red — the toggle landed on
 * the second SCBase window. If it were a no-op (e.g. wrong SCBase xor), both
 * would render white and this fails.
 *
 * Core-free section (always runs) pins the generated TEXT: `vram_toggle` +
 * `pad_read` are present when an alt map exists, `vram_toggle` EORs $2107 by
 * the correct SCBase delta, and NEITHER routine writes $2100 (so the existing
 * blanking-order invariants in vram-glue-fix.test.ts stay intact).
 */
import { describe, expect, it, beforeAll } from 'vitest';
import { existsSync, readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

import { WasmCore } from '../src/core/wasm-core';
import type { S9xModule } from '../src/core/wasm-core';
import { assemble } from '../src/asm/assembler';
import { buildRom } from '../src/asm/rom';
import { buildVramCompact, vramGlue } from '../src/gfx/vram';
import type { Rgb15 } from '../src/gfx/palette';
import type { TilemapEntry } from '../src/gfx/tilemap';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '..');
const JS = resolve(root, 'public/core/build/snes9x.js');
const WASM = resolve(root, 'public/core/build/snes9x.wasm');
const haveBuild = existsSync(JS) && existsSync(WASM);

// ---------------------------------------------------------------------------
// Two SOLID screens: primary = tile 0 (white), alt = tile 1 (red).
// ---------------------------------------------------------------------------

function twoScreenGraphics() {
  const size = 8; // mode 0 → 4-bit 8×8 tiles
  const solid = (idx: number): number[][] =>
    Array.from({ length: size }, () => Array.from({ length: size }, () => idx));
  const tiles = [solid(1), solid(2)]; // tile 0 = palette idx 1 (white), tile 1 = palette idx 2 (red)
  const palette: Rgb15[] = Array.from({ length: 16 }, (_, i) => {
    if (i === 0) return { r: 0, g: 0, b: 0, transparent: true };
    if (i === 1) return { r: 31, g: 31, b: 31, transparent: false }; // white
    if (i === 2) return { r: 31, g: 0, b: 0, transparent: false }; // red
    return { r: 0, g: 0, b: 0, transparent: false }; // opaque black
  });
  const full = (tile: number): TilemapEntry[] =>
    Array.from({ length: 1024 }, () => ({ tile, palette: 0, flipX: false, flipY: false, priority: false }));
  return { tiles, palette, primary: full(0), alt: full(1) };
}

/** Compose program + glue (with alt map) into a 256 KB SFC. */
function composeRom(program: string, glue: string, blob: Uint8Array): Uint8Array {
  const r = assemble(program + '\n' + glue, 0x008000, { 'vram.bin': blob });
  if (!r.ok) throw new Error('assemble failed: ' + r.errors.map((e) => `${e.line}: ${e.message}`).join('; '));
  return buildRom(r.bytes, { title: 'TOGGLE' });
}

// --- core-free: the generated glue TEXT is correct -------------------------

describe('vramGlue — service routines (core-free)', () => {
  const { tiles, palette, primary, alt } = twoScreenGraphics();
  const compact = buildVramCompact({
    mode: 0, tiles, palettes: [palette], tilemap: primary, altTilemap: alt,
    tileBase: 0, paletteBase: 0, mapBase: 0x8000,
  });

  it('reports two distinct SCBase windows (primary + one window past)', () => {
    expect(compact.mapBase).toBeGreaterThanOrEqual(0x1000);
    expect(compact.altMapBase).toBe(compact.mapBase + 0x1000);
    expect(compact.altMapBase).toBeLessThanOrEqual(0x7000);
  });

  it('emits pad_read (always) and vram_toggle (alt present) — via absolute SCBase writes', () => {
    const g = vramGlue(compact.mapBase, compact.bgmode, compact.blocks, 'vram.bin', compact.altMapBase);
    expect(g).toContain('pad_read:');
    expect(g).toContain('vram_toggle:');
    // The toggle writes the target map's SCBase byte to $2107 (an absolute write).
    expect(g).toMatch(/vram_toggle:[\s\S]*?sta \$2107[\s\S]*?rts/);
    // Crucially it NEVER reads $2107 back: this snes9x fork returns OpenBus
    // garbage on PPU register reads, so a read-modify-write silently no-ops.
    expect(g).not.toContain('lda $2107');
  });

  it('vram_toggle writes each map\'s absolute SCBase byte and flips a $2a state flag', () => {
    const g = vramGlue(compact.mapBase, compact.bgmode, compact.blocks, 'vram.bin', compact.altMapBase);
    // `hre` escapes the `$` so the byte is a literal match (in a regex, an
    // unescaped `$1` is treated as an anchor-context, not a literal dollar).
    const hre = (n: number) => '\\$' + n.toString(16).padStart(2, '0');
    const scByte = (compact.mapBase >> 9) & 0x7c;
    const altScByte = (compact.altMapBase! >> 9) & 0x7c;
    // The two maps live in DIFFERENT SCBase windows (that's the point of a toggle).
    expect(scByte).not.toBe(altScByte);
    // Each map is selected by writing ITS absolute SCBase byte to $2107.
    expect(g).toMatch(new RegExp(`lda #${hre(altScByte)}[\\s\\S]*?sta \\$2107`));
    expect(g).toMatch(new RegExp(`lda #${hre(scByte)}[\\s\\S]*?sta \\$2107`));
    // The flip is STATEFUL (zero-page $2a, toggled by `eor #$01`) — not a
    // read-modify-write of the PPU register.
    expect(g).toContain('eor #$01');
    expect(g).toMatch(/sta \$2a/);
    expect(g).toMatch(/lda \$2a/);
  });

  it('NO alt map → NO vram_toggle label (single-screen build stays clean)', () => {
    const { tiles, palette, primary } = twoScreenGraphics();
    const compact = buildVramCompact({ mode: 0, tiles, palettes: [palette], tilemap: primary });
    expect(compact.altMapBase).toBeUndefined();
    const g = vramGlue(compact.mapBase, compact.bgmode, compact.blocks, 'vram.bin', compact.altMapBase);
    expect(g).not.toContain('vram_toggle:');
    // pad_read is still there — it is the OS library, present for every build.
    expect(g).toContain('pad_read:');
  });

  it('neither routine writes $2100 (blanking-order invariants untouched)', () => {
    const g = vramGlue(compact.mapBase, compact.bgmode, compact.blocks, 'vram.bin', compact.altMapBase);
    // Isolate the region AFTER the last `vram_done:` (the service routines live there).
    const done = g.lastIndexOf('vram_done:');
    const tail = g.slice(done);
    // The ONLY $2100 write in the whole file is the final unblank right after
    // `vram_done:` — nothing in pad_read / vram_toggle touches it.
    expect(tail.match(/sta \$2100/g)).toHaveLength(1);
    expect(g.match(/sta \$2100/g)).toHaveLength(2); // first = forced-blank ON, last = unblank
  });
});

// --- real core: the toggle flips the display to the alt screen -------------

describe.skipIf(!haveBuild)('vram_toggle on the REAL snes9x core', () => {
  let M: S9xModule;
  let core: WasmCore;

  beforeAll(async () => {
    const src = readFileSync(JS, 'utf8');
    const factory = new Function(`${src}\n;return snesWasm;`)() as unknown as (m: object) => Promise<S9xModule>;
    const wasmB64 = readFileSync(WASM, 'base64');
    M = await factory({
      locateFile: (f: string) => (f === 'snes9x.wasm' ? `data:application/wasm;base64,${wasmB64}` : f),
      print: () => {}, printErr: () => {}, out: () => {}, err: () => {},
    });
    core = new WasmCore(M, []);
  }, 60_000);

  /** Run a ROM and report average screen RGB + non-black count. */
  async function runAndProbe(rom: Uint8Array, frames = 4) {
    await core.loadRom(rom);
    for (let i = 0; i < frames; i++) core.frame();
    const vf = core.lastVideo();
    let r = 0, g = 0, b = 0, nonBlack = 0;
    const total = vf.data.length / 4;
    for (let i = 0; i < vf.data.length; i += 4) {
      const pr = vf.data[i], pg = vf.data[i + 1], pb = vf.data[i + 2];
      r += pr; g += pg; b += pb;
      if (pr !== 0 || pg !== 0 || pb !== 0) nonBlack++;
    }
    return { r: r / total, g: g / total, b: b / total, nonBlack, total };
  }

  it('A (no toggle) = WHITE, B (toggle once) = RED — the flip lands on the alt map', async () => {
    const { tiles, palette, primary, alt } = twoScreenGraphics();
    const compact = buildVramCompact({
      mode: 0, tiles, palettes: [palette], tilemap: primary, altTilemap: alt,
      tileBase: 0, paletteBase: 0, mapBase: 0x8000,
    });
    const glue = vramGlue(compact.mapBase, compact.bgmode, compact.blocks, 'vram.bin', compact.altMapBase);

    const romA = composeRom(['JSR vram_load', 'idle:', 'BRA idle'].join('\n'), glue, compact.blob);
    const romB = composeRom(['JSR vram_load', 'JSR vram_toggle', 'idle:', 'BRA idle'].join('\n'), glue, compact.blob);

    const A = await runAndProbe(romA);
    const B = await runAndProbe(romB);
    console.log(
      `[A no-toggle] avg rgb=(${A.r.toFixed(1)},${A.g.toFixed(1)},${A.b.toFixed(1)}) non-black=${A.nonBlack}/${A.total}`,
      `[B toggled ] avg rgb=(${B.r.toFixed(1)},${B.g.toFixed(1)},${B.b.toFixed(1)}) non-black=${B.nonBlack}/${B.total}`,
    );

    // Both screens render (non-black) — the PPU is up and showing a tilemap.
    expect(A.nonBlack).toBeGreaterThan(A.total * 0.5);
    expect(B.nonBlack).toBeGreaterThan(B.total * 0.5);

    // A = white: all three channels high.
    expect(A.r).toBeGreaterThan(200);
    expect(A.g).toBeGreaterThan(200);
    expect(A.b).toBeGreaterThan(200);

    // B = red: R high, G and B low (the toggle moved the display to the alt map).
    expect(B.r).toBeGreaterThan(200);
    expect(B.g).toBeLessThan(60);
    expect(B.b).toBeLessThan(60);

    // The differential: same blob + glue, only the toggle call differs → colors differ.
    expect(A.g).not.toBeCloseTo(B.g, -1);
  }, 90_000);
});

describe('harness availability', () => {
  it('records whether the wasm build is present (so CI degrades, not breaks)', () => {
    expect(haveBuild).toBeTypeOf('boolean');
    if (!haveBuild) console.warn('[vram-toggle] snes9x.{js,wasm} absent — skipping real-core runs');
  });
});
